version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-nestjs-image:latest
    container_name: template-nestjs-container
    ports:
      - 3001:3000