version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-fastapi-image:latest
    container_name: template-fastapi-container
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080