version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-flask-image:latest
    container_name: template-flask-container
    ports:
      - 8080:8080
    environment:
      - PORT=8080