FROM node:20-alpine

WORKDIR /app

# create a nextjs project called myapp, you can refer
RUN npx create-next-app@latest myapp --js --tailwind --eslint --use-npm
# RUN npm i
# EXPOSE 3000

# CMD [ "pm2-runtime", "start", "bin/www" ]


